export const GET_ALL_NOTICES = "GET_ALL_NOTICES";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS";
export const GET_ALL_MATCHES = "GET_ALL_MATCHES";

export const CREATE_NOTICE = "CREATE_NOTICE";
export const CREATE_TEAM = "CREATE_TEAM";
export const CREATE_MATCH = "CREATE_MATCH";

export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";

export const GET_NOTICE_DETAIL = "GET_NOTICE_DETAIL";

export const POST_IMAGE = "POST_IMAGE";

export const CLEAR_STATE = "CLEAR_STATE";
export const COPY_ALL = "COPY_ALL";

/* FIXTURES 2024 */
export const CREATE_FIXTURE = "CREATE_FIXTURE";
export const GET_FIXTURES = "GET_FIXTURES";
export const GET_POSITIONS = "GET_POSITIONS";
export const GET_GENERAL_POSITIONS = "GET_GENERAL_POSITIONS";
